export function startPortfolio() {
  var ac = new AbortController();
  var rafIds = [];
  var nativeRaf = window.requestAnimationFrame.bind(window);
  function trackRaf(fn) {
    var id = nativeRaf(function (t) {
      if (ac.signal.aborted) return;
      fn(t);
    });
    rafIds.push(id);
    return id;
  }
  var origAdd = EventTarget.prototype.addEventListener;
  EventTarget.prototype.addEventListener = function (type, listener, options) {
    var opts =
      options && typeof options === "object"
        ? Object.assign({}, options, { signal: ac.signal })
        : { capture: Boolean(options), signal: ac.signal };
    return origAdd.call(this, type, listener, opts);
  };
  try {

      var reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      var projects=(window.__PORTFOLIO_PROJECTS||[]).map(function(p){return {id:p.id,n:p.n,c:p.c,t:p.t,l:p.l||"",d:p.d||"",s:Array.isArray(p.s)?p.s:[],u:p.u||"",tone:p.tone||"#9b6cff",imgs:Array.isArray(p.imgs)?p.imgs:[],cover:p.cover||(p.imgs&&p.imgs[0])||"",date:p.date||"2024-01-01",featured:Number(p.featured)||0};});
      projects.sort(function(a,b){if(a.featured||b.featured){if(a.featured&&b.featured)return a.featured-b.featured;return a.featured?-1:1}return b.date.localeCompare(a.date)});
      function syncProjectCounts(){var n=String(projects.length);var walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);var nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(function(node){if(!node.nodeValue||!/\b45\b/.test(node.nodeValue))return;var context=node.parentElement?node.parentElement.textContent:"";if(node.nodeValue.trim()!=="45"&&!/project|\bAll\b/i.test(context))return;if(/years|20\d{2}/i.test(context))return;node.nodeValue=node.nodeValue.replace(/\b45\b/g,n);});}
      syncProjectCounts();
      function formatDate(value){var parts=value.split('-'),months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return months[Number(parts[1])-1]+' '+Number(parts[2])+', '+parts[0]}
      function esc(s){return s.replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
      function renderArchive(target,prefix){var datedGroupAdded=false;target.innerHTML='<div class="archive-group-label" id="'+prefix+'-featured-projects-label"><div><div class="kicker">Pinned selection</div><h2>Featured projects</h2></div><p>Signature work, chosen to lead the archive.</p></div>';projects.forEach(function(p,i){if(!p.featured&&!datedGroupAdded){var group=document.createElement('div');group.className='archive-group-label';group.id=prefix+'-dated-projects-label';group.innerHTML='<div><div class="kicker">Complete archive</div><h2>Newest to oldest</h2></div><p>Published dates from the original WordPress portfolio.</p>';target.appendChild(group);datedGroupAdded=true}var a=document.createElement('article');a.className='archive-card reveal'+((p.cover||(p.imgs&&p.imgs.length))?' has-preview':'')+(p.featured?' pinned':'');a.dataset.category=p.c;a.dataset.search=(p.n+' '+p.t+' '+p.s.join(' ')).toLowerCase();a.dataset.project=String(i);a.style.setProperty('--card-tone',p.tone);a.tabIndex=0;a.setAttribute('role','button');a.setAttribute('aria-label','Open '+p.n+' project details');var cover=p.cover||(p.imgs&&p.imgs[0]);var pin=p.featured?'<span class="archive-pin">Featured</span>':'';var visual=cover?'<img src="'+esc(cover)+'" alt="'+esc(p.n)+' interface preview" loading="lazy">'+pin+'<span class="archive-open">'+((p.imgs&&p.imgs.length>1)?p.imgs.length+' images':'View project')+' ↗</span>':'<div class="project-art"></div>'+pin+'<span class="archive-open">Project details ↗</span>';var source='<div class="archive-links">'+(p.u?'<a class="archive-link" href="'+esc(p.u)+'" target="_blank" rel="noopener"><span>View on GitHub</span><span>↗</span></a>':'')+'<a class="archive-link" href="/work/'+encodeURIComponent(p.id)+'"><span>Project page</span><span>↗</span></a></div>';a.innerHTML='<div class="archive-visual">'+visual+'<span class="archive-num">'+String(i+1).padStart(2,'0')+' / '+projects.length+'</span></div><div class="archive-body"><div class="archive-type"><span>'+esc(p.t)+'</span><time datetime="'+p.date+'">'+formatDate(p.date)+'</time></div><h3>'+esc(p.n)+'</h3><p>'+esc(p.l||p.d)+'</p><div class="archive-tags">'+p.s.map(function(x){return '<span class="tag">'+esc(x)+'</span>'}).join('')+'</div>'+source+'</div>';target.appendChild(a)})}
      var grid=document.getElementById('project-grid'),homeGrid=document.getElementById('home-project-grid');
      renderArchive(grid,'projects');renderArchive(homeGrid,'home');

      function splitHeroLetters(){
        var title=document.querySelector('.hero h1');if(!title)return;
        title.setAttribute('aria-label',title.textContent.replace(/\s+/g,' ').trim());
        var nodes=[],walker=document.createTreeWalker(title,NodeFilter.SHOW_TEXT,{acceptNode:function(node){return /\S/.test(node.nodeValue)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});while(walker.nextNode())nodes.push(walker.currentNode);
        var index=0;nodes.forEach(function(node){var frag=document.createDocumentFragment();Array.from(node.nodeValue).forEach(function(ch){var span=document.createElement('span');span.className='hero-char'+(/\s/.test(ch)?' hero-space':'');span.setAttribute('aria-hidden','true');span.style.setProperty('--char-i',index++);span.textContent=/\s/.test(ch)?'\u00a0':ch;frag.appendChild(span)});node.parentNode.replaceChild(frag,node)});
        title.classList.add('hero-type','hero-animate');
      }
      function splitWords(el){
        if(!el||el.classList.contains('text-reveal'))return;var label=el.textContent.replace(/\s+/g,' ').trim(),nodes=[],walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT,{acceptNode:function(node){return /\S/.test(node.nodeValue)&&!node.parentElement.closest('.motion-word,svg')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});while(walker.nextNode())nodes.push(walker.currentNode);var index=0;
        nodes.forEach(function(node){var frag=document.createDocumentFragment();node.nodeValue.split(/(\s+)/).forEach(function(part){if(!part)return;if(/^\s+$/.test(part)){frag.appendChild(document.createTextNode(part));return}var span=document.createElement('span');span.className='motion-word';span.setAttribute('aria-hidden','true');span.style.setProperty('--word-i',index++);span.textContent=part;frag.appendChild(span)});node.parentNode.replaceChild(frag,node)});
        if(label)el.setAttribute('aria-label',label);el.classList.add('text-reveal');
      }
      function prepareTextMotion(){
        splitHeroLetters();
        document.querySelectorAll('.section-title,.page-hero h1,.contact-title,.manifesto,.subhead,.cta-link>span,.archive-group-label h2,.service h3,.timeline-item h3,.education h3,.language b').forEach(splitWords);
        document.querySelectorAll('.section-head .kicker,.page-hero .kicker,.about-preview .kicker,.cta-section .kicker').forEach(splitWords);
        document.querySelectorAll('.section-head>p,.page-hero p,.about-preview p,.body-copy,.contact-intro').forEach(function(el){el.classList.add('text-reveal','copy-reveal')});
        var heroLede=document.querySelector('.hero-lede');if(heroLede)heroLede.classList.add('hero-copy-motion');
        document.body.classList.add('motion-ready','text-motion-ready');
      }
      prepareTextMotion();

      function bindDepth(){if(reduce||!matchMedia('(pointer:fine)').matches)return;document.querySelectorAll('.archive-card,.service,.education,.language').forEach(function(el){el.addEventListener('pointermove',function(e){var r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;el.style.setProperty('--ry',((x-.5)*5.5).toFixed(2)+'deg');el.style.setProperty('--rx',((.5-y)*5.5).toFixed(2)+'deg');el.style.setProperty('--glow-x',(x*100).toFixed(1)+'%');el.style.setProperty('--glow-y',(y*100).toFixed(1)+'%')});el.addEventListener('pointerleave',function(){el.style.setProperty('--ry','0deg');el.style.setProperty('--rx','0deg')})});document.querySelectorAll('.button,.filter,.case-step').forEach(function(el){el.addEventListener('pointermove',function(e){var r=el.getBoundingClientRect();el.style.setProperty('--shine-x',(((e.clientX-r.left)/r.width)*100).toFixed(1)+'%')})})}
      bindDepth();
      var hero=document.querySelector('.hero');if(hero&&!reduce&&matchMedia('(pointer:fine)').matches){hero.addEventListener('pointermove',function(e){var r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;hero.style.setProperty('--hero-x',(x*32).toFixed(1)+'px');hero.style.setProperty('--hero-y',(y*25).toFixed(1)+'px');hero.style.setProperty('--hero-rx',(-y*4.2).toFixed(2)+'deg');hero.style.setProperty('--hero-ry',(x*5.2).toFixed(2)+'deg');hero.style.setProperty('--hero-px',((x+.5)*100).toFixed(1)+'%');hero.style.setProperty('--hero-py',((y+.5)*100).toFixed(1)+'%')});hero.addEventListener('pointerleave',function(){['--hero-x','--hero-y'].forEach(function(k){hero.style.setProperty(k,'0px')});['--hero-rx','--hero-ry'].forEach(function(k){hero.style.setProperty(k,'0deg')})})}

      var modal=document.getElementById('case-modal'),modalMedia=document.getElementById('case-media'),modalTitle=document.getElementById('case-title'),modalType=document.getElementById('case-type'),modalDescription=document.getElementById('case-description'),modalTags=document.getElementById('case-tags'),modalLink=document.getElementById('case-link'),modalCount=document.getElementById('case-count'),modalPosition=document.getElementById('case-position'),modalFocus=document.getElementById('case-focus'),lastFocus=null,currentProject=0,currentImage=0;
      function galleryFor(p){var images=p.imgs&&p.imgs.length?p.imgs:(p.img?[p.img]:[]);if(p.cover&&images.indexOf(p.cover)===-1)images=[p.cover].concat(images);return images}
      function renderGallery(){var p=projects[currentProject],images=galleryFor(p);if(!images.length){modalMedia.innerHTML='<div class="case-placeholder" style="--card-tone:'+esc(p.tone)+'"><div class="case-placeholder-inner"><div class="project-art"></div><h3>Project details</h3><p>This code-first project does not have a published interface gallery yet.</p></div></div>';return}var thumbs=images.length>1?'<div class="case-thumbs">'+images.map(function(src,i){return '<button class="case-thumb '+(i===currentImage?'active':'')+'" type="button" data-image="'+i+'" aria-label="Show image '+(i+1)+'"><img src="'+esc(src)+'" alt=""></button>'}).join('')+'</div>':'';modalMedia.innerHTML='<div class="case-stage"><span class="gallery-badge">Image '+(currentImage+1)+' / '+images.length+'</span><img src="'+esc(images[currentImage])+'" alt="'+esc(p.n)+' interface, view '+(currentImage+1)+'"><button class="gallery-arrow prev" type="button" aria-label="Previous image" '+(images.length<2?'hidden':'')+'>‹</button><button class="gallery-arrow next" type="button" aria-label="Next image" '+(images.length<2?'hidden':'')+'>›</button></div>'+thumbs}
      function showImage(step){var images=galleryFor(projects[currentProject]);if(images.length<2)return;currentImage=(currentImage+step+images.length)%images.length;renderGallery()}
      function openCase(p,index,keepOpen){if(!p)return;if(!keepOpen)lastFocus=document.activeElement;currentProject=index;currentImage=0;modalTitle.textContent=p.n;modalType.textContent=p.t+' · Full presentation';modalDescription.textContent=p.d;modalTags.innerHTML=p.s.map(function(x){return '<span class="tag">'+esc(x)+'</span>'}).join('');modalLink.hidden=!p.u;modalLink.href=p.u||'#';var pageLink=document.getElementById('case-page');if(pageLink)pageLink.href='/work/'+encodeURIComponent(p.id);modalPosition.textContent=String(index+1).padStart(2,'0')+' of '+String(projects.length).padStart(2,'0');modalFocus.textContent=p.c.split(' ').map(function(x){return x.toUpperCase()}).join(' · ');modalCount.textContent=(galleryFor(p).length?galleryFor(p).length+' published image'+(galleryFor(p).length>1?'s':''):'No published interface images')+' · Full description and stack';renderGallery();if(!keepOpen){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');trackRaf(function(){modal.classList.add('visible');modal.querySelector('.case-close').focus()})}}
      function moveProject(step){var next=(currentProject+step+projects.length)%projects.length;openCase(projects[next],next,true);modal.querySelector('.case-content').scrollTop=0}
      function closeCase(){modal.classList.remove('visible');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');setTimeout(function(){modal.classList.remove('open');modalMedia.innerHTML='';if(lastFocus&&lastFocus.focus)lastFocus.focus()},300)}
      function bindArchive(target){target.addEventListener('click',function(e){var link=e.target.closest('.archive-link');if(link)return;var card=e.target.closest('.archive-card');if(card)openCase(projects[Number(card.dataset.project)],Number(card.dataset.project))});target.addEventListener('keydown',function(e){var card=e.target.closest('.archive-card');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openCase(projects[Number(card.dataset.project)],Number(card.dataset.project))}})}
      bindArchive(grid);bindArchive(homeGrid);
      modal.querySelector('.case-close').addEventListener('click',closeCase);modal.querySelector('.case-back').addEventListener('click',closeCase);modal.querySelector('.project-prev').addEventListener('click',function(){moveProject(-1)});modal.querySelector('.project-next').addEventListener('click',function(){moveProject(1)});modalMedia.addEventListener('click',function(e){var thumb=e.target.closest('.case-thumb');if(thumb){currentImage=Number(thumb.dataset.image);renderGallery();return}if(e.target.closest('.gallery-arrow.prev'))showImage(-1);if(e.target.closest('.gallery-arrow.next'))showImage(1)});modal.addEventListener('click',function(e){if(e.target===modal)closeCase()});document.addEventListener('keydown',function(e){if(!modal.classList.contains('open'))return;if(e.key==='Escape')closeCase();else if(e.key==='ArrowLeft')showImage(-1);else if(e.key==='ArrowRight')showImage(1)});

      var pre=document.querySelector('.preloader'),count=document.querySelector('.pre-count'),bar=document.querySelector('.pre-bar');if(!reduce){var preStart=performance.now();(function loadFrame(now){var elapsed=now-preStart,progress=Math.min(1,elapsed/920),eased=1-Math.pow(1-progress,3),n=Math.round(eased*100);count.textContent=String(n).padStart(2,'0');bar.style.width=n+'%';if(progress<1)trackRaf(loadFrame);else setTimeout(function(){pre.classList.add('done')},140)})(preStart)}else{pre.classList.add('done')}
      var pages=[].slice.call(document.querySelectorAll('.page')),links=[].slice.call(document.querySelectorAll('[data-route]')),observer,revealFallback;
      function showMotionElement(el){if(el.classList.contains('reveal'))el.classList.add('in');if(el.classList.contains('text-reveal'))el.classList.add('text-in')}
      function observe(){if(observer)observer.disconnect();if(revealFallback)clearTimeout(revealFallback);var active=document.querySelector('.page.active');if(!active)return;var els=active.querySelectorAll('.reveal,.text-reveal');if(reduce){els.forEach(showMotionElement);return}observer=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){showMotionElement(e.target);observer.unobserve(e.target)}})},{threshold:.08,rootMargin:'0px 0px -4% 0px'});els.forEach(function(el){observer.observe(el)});revealFallback=setTimeout(function(){els.forEach(showMotionElement)},5200)}
      var countLabel=String(projects.length);var routeMeta={home:{title:'Nour El Houda Bouajila | Full-Stack Engineer in Hamilton',description:'Portfolio of '+countLabel+' web, AI, cloud, analytics and WordPress projects by Nour El Houda Bouajila, a full-stack engineer in Hamilton, Ontario.'},projects:{title:'Projects | Nour El Houda Bouajila',description:'Explore '+countLabel+' original web, AI, cloud, analytics, e-commerce and WordPress projects with screenshots, descriptions and source links.'},about:{title:'About | Nour El Houda Bouajila, Full-Stack Engineer',description:'Experience, education, technical skills and professional background of full-stack engineer Nour El Houda Bouajila in Hamilton, Ontario.'},contact:{title:'Contact | Nour El Houda Bouajila',description:'Contact Nour El Houda Bouajila in Hamilton for full-stack engineering, React, Node.js, cloud, AI and WordPress work.'}};
      function updateMeta(selector,value){var node=document.querySelector(selector);if(node)node.setAttribute('content',value)}
      var routedOnce=false,routeWipe=document.querySelector('.route-wipe');function route(){var name=(location.hash.replace('#/','')||'home').split('/')[0];if(!pages.some(function(p){return p.dataset.page===name}))name='home';if(routedOnce&&!reduce){routeWipe.classList.remove('play');void routeWipe.offsetWidth;routeWipe.classList.add('play');setTimeout(function(){routeWipe.classList.remove('play')},760)}pages.forEach(function(p){p.classList.toggle('active',p.dataset.page===name)});links.forEach(function(a){a.classList.toggle('active',a.dataset.route===name)});scrollTo(0,0);var meta=routeMeta[name];document.title=meta.title;updateMeta('meta[name="description"]',meta.description);updateMeta('meta[property="og:title"]',meta.title);updateMeta('meta[property="og:description"]',meta.description);updateMeta('meta[name="twitter:title"]',meta.title);updateMeta('meta[name="twitter:description"]',meta.description);routedOnce=true;trackRaf(observe)}
      addEventListener('hashchange',route);route();
      var currentFilter='all',search=document.querySelector('.search'),empty=document.getElementById('project-empty'),visibleCount=document.getElementById('visible-count');function applyFilter(){var q=search.value.trim().toLowerCase(),visible=0,featuredVisible=0,datedVisible=0;grid.querySelectorAll('.archive-card').forEach(function(card){var cat=currentFilter==='all'||card.dataset.category.split(' ').indexOf(currentFilter)>-1;var text=!q||card.dataset.search.indexOf(q)>-1;var show=cat&&text;card.classList.toggle('hidden',!show);if(show){visible++;card.classList.add('in');if(card.classList.contains('pinned'))featuredVisible++;else datedVisible++}});document.getElementById('projects-featured-projects-label').classList.toggle('hidden',featuredVisible===0);document.getElementById('projects-dated-projects-label').classList.toggle('hidden',datedVisible===0);empty.classList.toggle('show',visible===0);visibleCount.textContent=visible+' / '+projects.length+' projects'}
      document.querySelectorAll('.filter').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.filter').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');currentFilter=btn.dataset.filter;applyFilter()})});search.addEventListener('input',applyFilter);
      var pointer={x:innerWidth*.5,y:innerHeight*.35,active:false};if(!reduce&&matchMedia('(pointer:fine)').matches){var dot=document.querySelector('.cursor-dot'),halo=document.querySelector('.cursor-halo'),cursorLabel=document.querySelector('.cursor-label'),mx=pointer.x,my=pointer.y,hx=mx,hy=my;addEventListener('pointermove',function(e){mx=e.clientX;my=e.clientY;pointer.x=mx;pointer.y=my;pointer.active=true;document.body.style.setProperty('--pointer-x',mx+'px');document.body.style.setProperty('--pointer-y',my+'px');dot.style.transform='translate3d('+(mx-3.5)+'px,'+(my-3.5)+'px,0)';cursorLabel.style.transform='translate3d('+(mx-24)+'px,'+(my-5)+'px,0)'});(function cursorLoop(){hx+=(mx-hx)*.16;hy+=(my-hy)*.16;halo.style.transform='translate3d('+(hx-21)+'px,'+(hy-21)+'px,0)';trackRaf(cursorLoop)})();document.querySelectorAll('a,button,input').forEach(function(el){el.addEventListener('mouseenter',function(){document.body.classList.add('cursor-active')});el.addEventListener('mouseleave',function(){document.body.classList.remove('cursor-active')})});document.querySelectorAll('.archive-card').forEach(function(el){el.addEventListener('mouseenter',function(){cursorLabel.textContent='Explore';document.body.classList.add('cursor-project')});el.addEventListener('mouseleave',function(){document.body.classList.remove('cursor-project')})});document.querySelectorAll('.portrait-shell').forEach(function(el){el.addEventListener('mouseenter',function(){cursorLabel.textContent='Nour';document.body.classList.add('cursor-project')});el.addEventListener('mouseleave',function(){document.body.classList.remove('cursor-project')})});document.querySelectorAll('.magnetic').forEach(function(el){el.addEventListener('mousemove',function(e){var r=el.getBoundingClientRect();el.style.transform='translate3d('+((e.clientX-r.left-r.width/2)*.13)+'px,'+((e.clientY-r.top-r.height/2)*.13)+'px,20px)'});el.addEventListener('mouseleave',function(){el.style.transform=''})})}
      var scrollTick=false;function updateScrollScene(){var max=Math.max(1,document.documentElement.scrollHeight-innerHeight),p=Math.min(1,scrollY/max);document.body.style.setProperty('--scroll-p',p.toFixed(4));if(!reduce){document.querySelector('.mesh').style.transform='translate3d(0,'+(scrollY*.055).toFixed(1)+'px,0)';document.querySelector('.grid-noise').style.transform='translate3d(0,'+(scrollY*.022).toFixed(1)+'px,0)'}scrollTick=false}addEventListener('scroll',function(){if(!scrollTick){scrollTick=true;trackRaf(updateScrollScene)}},{passive:true});updateScrollScene();
      var canvas=document.getElementById('field'),ctx=canvas.getContext('2d'),pts=[],w=0,h=0,dpr=1;function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);pts=[];var total=Math.min(68,Math.max(28,Math.floor(w/22)));for(var i=0;i<total;i++)pts.push({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22,r:Math.random()*1.25+.45})}function draw(){ctx.clearRect(0,0,w,h);var line=getComputedStyle(document.documentElement).getPropertyValue('--canvas-line').trim();for(var i=0;i<pts.length;i++){var p=pts[i],pdx=p.x-pointer.x,pdy=p.y-pointer.y,pdist=Math.sqrt(pdx*pdx+pdy*pdy)||1;if(pointer.active&&pdist<145){var force=(1-pdist/145)*.7;p.x+=pdx/pdist*force;p.y+=pdy/pdist*force}p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.globalAlpha=.58;ctx.fillStyle=line;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();if(pointer.active&&pdist<175){ctx.globalAlpha=(1-pdist/175)*.36;ctx.strokeStyle=line;ctx.beginPath();ctx.moveTo(pointer.x,pointer.y);ctx.lineTo(p.x,p.y);ctx.stroke()}for(var j=i+1;j<pts.length;j++){var q=pts[j],dx=p.x-q.x,dy=p.y-q.y,d=Math.sqrt(dx*dx+dy*dy);if(d<118){ctx.globalAlpha=(1-d/118)*.3;ctx.strokeStyle=line;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}}ctx.globalAlpha=1;if(pointer.active){var glow=ctx.createRadialGradient(pointer.x,pointer.y,0,pointer.x,pointer.y,90);glow.addColorStop(0,'rgba(34,211,238,.12)');glow.addColorStop(1,'rgba(34,211,238,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(pointer.x,pointer.y,90,0,Math.PI*2);ctx.fill()}if(!reduce)trackRaf(draw)}resize();draw();addEventListener('resize',resize);
    
  } finally {
    EventTarget.prototype.addEventListener = origAdd;
  }
  return function stopPortfolio() {
    ac.abort();
    rafIds.forEach(function (id) {
      cancelAnimationFrame(id);
    });
  };
}
